### ISSUE TITLE
Easyapache4 / cPanel

### ISSUE THREAD

**Issue by pingmurder** [BeAPI/phpwpinfo#10]
Please update your script or make it clear it's not fully compatible with cpanel hosting, the only Opcode caching currently compatible with cPanel release is OpCache which your script doesn't test for.

**Comment by herewithme** [comment]
Hum.

It's strange, because I test the presence of opcode cache PHPv5.5 and higher. (Zend Opcache)

Cf: https://github.com/BeAPI/phpwpinfo/blob/master/phpwpinfo.php#L186
