### ISSUE TITLE
Test remote IP from server and compared then with any public API

### ISSUE THREAD

**Issue by herewithme** [BeAPI/phpwpinfo#16]

**Comment by MaximeCulea** [comment]
Allow to check if AWS server use CDN ip (localhost) or the remote one for the client.

**Comment by herewithme** [comment]
Tests added with this commit : https://github.com/BeAPI/phpwpinfo/commit/742085e634c5dfe078f296c80d9aaf8f48bc8511

Ping @MaximeCulea
