### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by jmau111** [BeAPI/phpwpinfo#19]
Hi,

this line https://github.com/BeAPI/phpwpinfo/blob/master/phpwpinfo.php#L1062 is problematic if your server get hacked.

**Comment by MaximeCulea** [comment]
Maybe add a `checksum()` ?

**Comment by petitphp** [comment]
Or download it from Github directly instead ? https://github.com/funkatron/phpsecinfo

**Comment by asadowski10** [comment]
@jmau111 

We have just made a new release that removes this piece of code.

Thanks for your feedback :)
