### ISSUE TITLE
Apache Modules not recognized

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/phpwpinfo#32]
Hello there :wave: 
For the Apache Modules the Script states that there are some missing modules, however, they are loaded. They just have a different name, which can vary across distributions:

```
root [~] # apachectl -M |egrep -i 'deflate|env|expires|headers|filter|mime|rewrite|setenvif'
 deflate_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 mime_module (shared) 
```

**Comment by Rahe** [comment]
Hello,

What returns the function `apache_get_modules` ? the `env_module` etc. ?
Is the values pushed on the $_SERVER ?
The .htaccess file (https://github.com/BeAPI/phpwpinfo/blob/master/.htaccess#L13)  does work ?

**Comment by MaximeCulea** [comment]
Hello Nicolas :wave: 
The function apache_get_modules only works if PHP is running as an apache module (which is not the case anymore in most setups these days) and does not report anything when running as PHP-FPM or FastCGI. So far I could not find a reliable way to test for apache modules with PHP running on FPM/CGI.
The best option would maybe be to try to run the functions of these modules and catch the error message if they are not there.

**Comment by Rahe** [comment]
Hello Maxime,

Yes this is why we have the `.htaccess` file to be pushed alongside the phpwpinfo.php file that pushes the env variables in case of the Apache modules are loaded into Apache.
Can you check with the `.htaccess` file ?

On my side, if I add the .htacess alongside the phpwpinfo.php file everything is fine :

![Capture d’écran 2022-07-05 à 10 04 52](https://user-images.githubusercontent.com/1007502/177281005-f8db1df1-791c-4383-811d-a0e6d58084da.png)
![Capture d’écran 2022-07-05 à 10 04 59](https://user-images.githubusercontent.com/1007502/177281010-bb7795ef-4659-4785-921a-bbe5e46f5224.png)

**Comment by MaximeCulea** [comment]
I have created the .htaccess file, it is working. Thank you!
As the installation tells to get the PHP file, I suppose that about the htaccess that is not documented :)

**Comment by Rahe** [comment]
Great, we'll update the installation process i this way ;)
